import sys
from pathlib import Path, PurePath
from dataclasses import dataclass, field
# Find path to root folder
rootFolder = 'sounds-phd'
pathToRoot = Path(__file__)
while PurePath(pathToRoot).name != rootFolder:
    pathToRoot = pathToRoot.parent
sys.path.append(f'{pathToRoot}/01_algorithms/01_NR/02_distributed')
from danse_testing import *
from danse_utilities.classes import SROsTimeVariation

@dataclass
class TestsParams:
    pathToASC: str = '' # path to acoustic scenario to consider
    computeCentralised: bool = False    # if True, compute centralised
    deltaSROs: list[int] = field(default_factory=list)  # list of SROs
        # ^^^ 2 simulations per element: w/ and w/out comp.
    exportBasePath: str = ''        # path to exported files
    timeVaryingSROs: bool = False   # if True, consider time-varying SROs
    noiseType: str = 'white'        # type of noise generated by noise source(s)


ASCBASEPATH = '02_data/01_acoustic_scenarios/for_submissions/icassp2023'
EXPORTPATH = '01_algorithms/01_NR/02_distributed/res/for_submissions/icassp2023'
PARAMS = TestsParams(
    # vvv 20 cm mic. spacing vvv
    pathToASC=f'{ASCBASEPATH}/J4Mk[1_3_2_5]_Ns1_Nn2/AS18_RT150ms',
    # vvv 10 cm mic. spacing vvv
    # pathToASC=f'{ASCBASEPATH}/J4Mk[1_3_2_5]_Ns1_Nn2/AS37_RT150ms',
    computeCentralised=True,
    deltaSROs=[0,20,50,200],
    exportBasePath=EXPORTPATH,
    timeVaryingSROs=False,
    # noiseType='white',      # white noise
    # noiseType='ssn',        # speech-shaped noise
    noiseType='babble',     # babble noise
)


def main():

    # Derive the number of simulations to conduct
    nTest = 2 * len(PARAMS.deltaSROs)
    if PARAMS.computeCentralised:
        nTest += 1

    # Derive the number of nodes
    nNodes = int(Path(PARAMS.pathToASC).parent.stem[1])

    # Adjust parameters depending on test
    for ii in range(nTest):
        # Compute SRO-free centralised estimate last, if asked
        if PARAMS.computeCentralised and ii == nTest - 1:
            params = dict([  # centralised case
                ('listedSROs', [0] * nNodes),
                ('comp', False),
                ('bc', 'wholeChunk'),
                ('computeCentrEstimate', True)
            ])
        else:
            lsros = [
                ((-1)**jj) * ((jj + 1) // 2) * PARAMS.deltaSROs[ii // 2]\
                    for jj in range(nNodes)
            ]
            if ii % 2 == 0:
                params = dict([  # do compensate SROs
                    ('listedSROs', lsros),
                    ('comp', True),
                    ('bc', 'samplePerSample'),
                    ('computeCentrEstimate', False)
                ])
            else:
                params = dict([  # don't compensate SROs
                    ('listedSROs', lsros),
                    ('comp', False),
                    ('bc', 'wholeChunk'),
                    ('computeCentrEstimate', False)
                ])
        
        # Commmon parameters in all cases
        params['ASC'] = PARAMS.pathToASC
        params['timeVaryingSROs'] = PARAMS.timeVaryingSROs
        params['noiseType'] = PARAMS.noiseType

        run_simul(params, PARAMS.exportBasePath)


def run_simul(params, exportBasePath):

    # Determine which noise to use
    if params['noiseType'] == 'white':
        noiseFiles = ['whitenoise_signal_1.wav', 'whitenoise_signal_2.wav']
    elif params['noiseType'] == 'ssn':
        noiseFiles = ['ssn/ssn_speech1.wav', 'ssn/ssn_speech2.wav']
    elif params['noiseType'] == 'babble':
        noiseFiles = ['babble/babble1.wav', 'babble/babble2.wav']

    # Generate test parameters
    danseTestingParams = sro_testing.DanseTestingParameters(
        # General hyperparameters
        writeOver=False,    # if True, the script will overwrite existing data
        #
        ascBasePath=f'{pathToRoot}/02_data/01_acoustic_scenarios/validations',
        signalsPath=f'{Path(__file__).parent}/validations/signals',
        #
        # vvvvvvvvvvvvvv
        specificAcousticScenario=[f'{pathToRoot}/{params["ASC"]}'],
        #
        fs=16000,
        specificDesiredSignalFiles=[
            f'{pathToRoot}/02_data/00_raw_signals/01_speech/{file}'\
                for file in ['speech1.wav', 'speech2.wav']
        ],
        specificNoiseSignalFiles=[
            f'{pathToRoot}/02_data/00_raw_signals/02_noise/{file}'\
                for file in noiseFiles
        ],
        sigDur=15,
        baseSNR=5,
        #
        SROsParams=TestSROs(
            type='specific',
            # vvvvvvvvvvvvvv
            listedSROs=params['listedSROs'],
        ),
        #
        timeBtwExternalFiltUpdates=3.,
        #
        # vvvvvvvvvvvvvv
        broadcastScheme=params['bc'],
        performGEVD=1,
        #
        computeLocalEstimate=True,
        # vvvvvvvvvvvvvv
        computeCentrEstimate=params['computeCentrEstimate'],
        #
        asynchronicity=SamplingRateOffsets(
            plotResult=True,
            # vvvvvvvvvvvvvv
            compensateSROs=params['comp'],
            estimateSROs='CohDrift',
            cohDriftMethod=CohDriftSROEstimationParameters(
                loop='open'
            ),
            timeVaryingSROs=SROsTimeVariation(
                # vvvvvvvvvvvvvv
                timeVarying=params['timeVaryingSROs']
            )
        ),
        printouts=PrintoutsParameters(
            progressPrintingInterval=0.5
        )
    )

    # Run test
    sro_testing.go(danseTestingParams, exportBasePath)


if __name__=='__main__':
    sys(exit(main()))