mcRuns: 1  # Number of Monte-Carlo runs
originalSeed: 0
refSensorIdx: 0  # Reference sensor index (for desired signal)
sigConfig:
  fs: 16000
  nSamplesBatch: 10000  # Total number of samples for batch processing
  # desiredSignalType: noise  # noise, speech, noise+pauses
  desiredSignalType: noise+pauses  # noise, speech, noise+pauses (only valid for online-mode)
  pauseLength: 20000  # [samples]
  pauseSpacing: 20000  # [samples]

K: 5  # Number of nodes
Mk: 3  # Number of microphones per node (same for all nodes)
# K: 15  # Number of nodes
# Mk: 5  # Number of microphones per node (same for all nodes)

# ---- Online processing
B: 500  # Block size (number of samples per block)
overlapB: 0  # Overlap between blocks (in percentage)
beta: 0.9  # Forgetting factor for online covariance matrix
betaRnn: 0.9  # Forgetting factor for Rnn

nStft: 1024  # STFT window length
nNoiseSources: 1  # Number of noise sources
eps: 0.0001  # Stopping criterion constant
maxIter: 500  # Maximum number of iterations
snr: 10  # [dB] SNR of desired signal
# snSnr: 5  # [dB] SNR of self-noise signals
snSnr: 20  # [dB] SNR of self-noise signals

algos:  # 'danse' and/or 'ti-danse'
- danse
- ti-danse

# mode: batch  # 'wola' or 'online' or 'batch'
mode: online  # 'wola' or 'online' or 'batch'

gevd: true  # Use MWF
# gevd: false  # Use MWF

nodeUpdating: seq  # Node-updating strategy: 'sim' or 'seq'
nIterBetweenUpdates: 0  # Number of iterations between node-updates (at each node)

# ----- External filter relaxation for simultaneous node-updating
betaExt: 0.7  # Forgetting factor for external filter relaxation
alphaExt: 0.5  # External filter relaxation factor
tExt: 0.4  # Update external filter every `TEXT` seconds

# ----- Tests / debug
# normGkEvery: 1  # Normalize `gk` coefficient every `NORM_GK_EVERY` iterations
normGkEvery: 9999  # Normalize `gk` coefficient every `NORM_GK_EVERY` iterations
# ----- Plot booleans
plotOnlyCost: true  # Plot only cost (no per-node MMSE)
exportFolder: './97_tests/09_tidanse/out'
